spring:
 boot: 
  admin:
   client:
    url: http://localhost:8081

management:
 endpoints:
  web:
   exposure:
    include: '*'
 metrics:
  export:
   prometheus:
    enabled: true
 endpoint:
  metrics:
   enabled: false
  prometheus:
   enabled: true

external-client:
 uri:  http://viacep.com.br/ws