spring:
 jmx:
   enabled: true
 boot: 
  admin:
   client:
    url: http://localhost:8081

management:
 endpoints:
  web:
   exposure:
    include: '*'
 metrics:
  export:
   prometheus:
    enabled: true
 endpoint:
  metrics:
   enabled: true
  prometheus:
   enabled: true
  logfile:
   external-file: logs/client.log

logging:
 file:
  name: logs/client.log


external-client:
 uri:  http://viacep.com.br/ws